GET http://localhost:8080/users
Accept: application/json

###

GET http://localhost:8080/users/someid
Accept: application/json

###

POST http://localhost:8080/users
Content-Type: application/json

{}

###

PUT http://localhost:8080/users/someid
Content-Type: application/json

{}

###

PATCH http://localhost:8080/users/someid
Content-Type: application/json

{}

###
